Fix missing astpretty dependency
Running the following in a clean virtualenv:
```
pip install flake8 flake8-expression-complexity
flake8
```

Results in an error like the following:
```
File ".../lib/python3.6/site-packages/flake8_expression_complexity/utils/complexity.py", line 5, in <module>
  from astpretty import pprint
ModuleNotFoundError: No module named 'astpretty'
```

This change adds `astpretty` and `flake8` as requirements for this
package, fixing this error.